version: 0.2
phases:
  install:
   runtime-versions:
     python: 3.9

  pre_build:
    commands:
      - cd canary-src
      - mkdir -p package

  build:
    commands:
      - echo Build started on `date`
      - pip3 install --upgrade pip
      - pip3 install --target ./package -r requirements.txt
      - cd package
      - zip -r ../index.zip .
      - cd ..
      - zip index.zip index.py
      - aws s3 cp index.zip s3://$BUCKET/canary.zip --sse aws:kms